# config/packages/security.yaml
security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        # désactive la sécurité sur le profiler et les assets
        dev:
            pattern:   ^/(_(profiler|wdt)|css|images|js)/
            security:  false

        main:

            lazy:     true
            provider: app_user_provider

            form_login:
                login_path:  app_login    # route GET/POST du login
                check_path:  app_login
                enable_csrf: true

            logout:
                path:   app_logout
                target: app_home

    # # ← bien placé sous "security:"
    # access_control:
    #     # 1) ces 3 URLs sont ouvertes à TOUS (même aux anonymous)
    #     - { path: ^/home$,     roles: IS_AUTHENTICATED_ANONYMOUSLY }
    #     - { path: ^/register$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    #     - { path: ^/login$,    roles: IS_AUTHENTICATED_ANONYMOUSLY }

    #     # 2) /profile accessible seulement quand ROLE_USER
    #     - { path: ^/profile,   roles: ROLE_USER }

    #     # 3) tout le reste (y compris /) exige ROLE_USER
    #     - { path: ^/,          roles: ROLE_USER }
