version: '3.8'

services:
  php:
    build: ./docker/php
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: 'mysql://symfony:Kaamelot59!@db:3306/vampire-v20?serverVersion=8.0&charset=utf8mb4'

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: vampire-v20
      MYSQL_USER: symfony
      MYSQL_PASSWORD: Kaamelot59!
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - db_data:/var/lib/mysql

  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

volumes:
  db_data: