name: Symfony CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: vampire-v20
          MYSQL_USER: symfony
          MYSQL_PASSWORD: Kaamelot59!
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping -h 127.0.0.1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: pdo_mysql
          coverage: none

      - name: Install Composer dependencies (without scripts)
        run: composer install --prefer-dist --no-progress --no-scripts


      - name: Create .env.test file
        run: |
          echo "APP_ENV=test" > .env.test
          echo "DATABASE_URL=mysql://symfony:Kaamelot59!@127.0.0.1:3306/vampire-v20?serverVersion=8.0&charset=utf8mb4" >> .env.test

      - name: Wait for MySQL to be ready
        run: sleep 10

      - name: Create database schema
        run: php bin/console doctrine:schema:create --env=test

      - name: Run PHPUnit tests
        run: php bin/phpunit
