name: Symfony CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: vampire-v20
          MYSQL_USER: symfony
          MYSQL_PASSWORD: Kaamelot59!
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping -h 127.0.0.1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: pdo_mysql
          coverage: none

      - name: Install Composer dependencies (sans scripts)
        run: composer install --prefer-dist --no-progress --no-scripts

      - name: Créer .env.test
        run: |
          echo "APP_ENV=test" > .env.test
          echo "DATABASE_URL=mysql://symfony:Kaamelot59!@127.0.0.1:3306/vampire-v20?serverVersion=8.0&charset=utf8mb4" >> .env.test

      - name: Attendre MySQL et créer la DB de test
        run: |
          sleep 10
          mysql -h 127.0.0.1 -uroot -proot \
            -e "CREATE DATABASE IF NOT EXISTS \`vampire-v20_test\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
                GRANT ALL PRIVILEGES ON \`vampire-v20_test\`.* TO 'symfony'@'%';"

      - name: Créer le schéma Doctrine (test)
        run: php bin/console doctrine:schema:create --env=test

      - name: Clear cache (test)
        run: php bin/console cache:clear --env=test

      - name: Lancer les tests
        run: php bin/phpunit
